### ISSUE TITLE
ApplicationSet v0.4.0 Release Checklist

### ISSUE THREAD

**Issue by jgwest** [argoproj/applicationset#532]
- [X] A `release-(numbered version)` branch exists in `argoproj/applicationset`
    - example: 'release-0.1.0'
    - [X] The release branch name should NOT contain the letter `v `(e.g. BAD: `release-v0.1.0`, not like this!)
    - [X] Confirm that, within the GitHub web UI, the branch says `This branch is 1 commit ahead of master. `, with that one commit being the release commit described below.

- A release commit exists as the most recent commit of the `release-(version)` branch:
    - [X]  A commit with the message of `Release (version)`
        - Example: `Release v0.1.0`
        - The version string SHOULD contain the letter `v`, as above. 
    - The commit should contain changes to:
        - [X] `manifests/install.yaml`
        - [X] `manifests/base/kustomization.yaml`
        - [X] `.github/workflows/ci-build.yaml`
        - [X] `docs/Getting-Started.md`
        - [X] `hack/verify-argo-cd-versions.sh`
- [X] A `v(version)` tag exists in the `argoproj/applicationset` repo
    - Example: `v0.1.0`
    - [X] Ensure it matches the release commit above
- [X] A `stable` tag exists, and points to the same release commit as above.

- [X] Ensure that a GitHub `v(version)` GitHub Release exists, pointing to the `v(version)` tag.
    - Tag must have `v` prefix, eg `v0.1.0`

- [X] Ensure that container image exists on quay.io with name 'argoproj/argocd-applicationset' 
    - [X] Appears here: https://quay.io/repository/argoproj/argocd-applicationset
    - [X] With tag `v(version)`, eg `v0.1.0`
        - [X] Tag must have `v` prefix, eg `v0.1.0`
    - [X] Verify that the tag update time references today's date
    - [X] Security scan should be green.

#### On the `release-(version)` branch:

- [X] Ensure the VERSION string matches the expected version
    - [X] The VERSION string should NOT begin with a `v`, (eg BAD: `v0.1.0`)
- [X] Ensure that `install.yaml` under `manifests/` points to the desired ApplicationSet version.

## Master branch checklist

- Ensure that a PR is opened on the **master** branch that:
    - [X] Increments the VERSION file (eg 0.1.0 to 0.2.0)
    - [X] Verify VERSION file does not contain the letter `v` as a prefix to the versio number
    - [X] Update the CI jobs in `.github/workflows` to point to the latest Argo CD version (Run `grep -r -i "argo-release"` to find the version list.)

## Doc checklist
- [X] Ensure that https://readthedocs.org/projects/argocd-applicationset/versions/ points to the correct commit (commit that is at the HEAD of the release branch), for the `stable` and `v(version)` versions.
- [X] Ensure that https://argocd-applicationset.readthedocs.io/ points to the new version, and contains the correct content 
    - **Note**: this may require a manually triggered build at rtd.io. See release process for details.
- [X] Ensure that the Getting Start page at rtd.io includes references to `kubectl apply` which points to the correct applicationset controller version
    - Ensure that *both* Section A and Section B (of Install) are updated from pointing to `master`, to pointing to `v(version)`. 
    - On [Stable](https://argocd-applicationset.readthedocs.io/en/stable/Getting-Started/)
    - On the version-specific page: `https://argocd-applicationset.readthedocs.io/en/(version)/Getting-Started/`
        - Example: `https://argocd-applicationset.readthedocs.io/en/v0.2.0/Getting-Started/`

#### In the GitHub Releases tag:
- [X] Ensure that the `v(version string)` release contains the features/change log for the particular version. This should be roughly the same content as goes into the CHANGELOG.md file.

#### On the `release-(version)` branch:    
- [X] Ensure that CHANGELOG.md includes the new version information
	
#### On the master branch:
- [X] Ensure that CHANGELOG.md includes the new version information

## Live image testing

- [X] Apply `install.yaml` on a cluster, and confirm that it installs the correct image version
    - [X] Confirm that all the pods start as expected.
    - [X] Confirm that the pod logs contain no errors
    - [X] Run ApplicationSet E2E tests against ApplicationSet controller installed via this method
    - [X] Confirm that the pod logs contain no errors after runnings the tests

## Communications

- [X] Publish blog post (if applicable)
- [X] Post to Slack

**Comment by jgwest** [comment]
Released :tada:
